name: 'Add Notebook Header'
description: 'Add a header cell (e.g. copyright) at the beginning of Jupyter noteooks if not present already.'
author: 'Vital de Nodrest (@vitaldenodrest)'

branding:
  icon: 'book-open'
  color: 'white'

inputs:
  cell_source:
    description: "The cell contents"
    required: true
  file_pattern:
    description: "The files to target (default: '*.ipynb')"
    required: false
    default: '*.ipynb'

runs:
  using: 'composite'
  steps:

    - name: Configure Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install packages
      shell: bash
      run: pip install nbformat

    - name: Prepend Header
      shell: bash

      run: |
        # Declare action parameters as env variables
        CELL_SOURCE="${{ inputs.cell_source }}"
        PATTERN="${{ inputs.file_pattern }}"

        # Configure Python
        pip install nbformat

        # Find relevant files
        # Avoid .git to keep the index safe
        find . -name "$PATTERN" -not -path "./.git/*" -type f | while read -r file; do

          echo "Processing $file..."
          
          # Run Python script
          python script.py

          echo $STATUS

        done