name: 'Add Notebook Header'
description: 'Add a header cell (e.g. copyright) at the beginning of Jupyter noteooks if not already present anywhere in the notebook.'
author: 'Vital de Nodrest (@vitaldenodrest)'

branding:
  icon: 'book-open'
  color: 'white'

inputs:
  cell_source:
    description: "The cell contents"
    required: true
  cell_metadata:
    description: "Cell metadata"
    required: false
    default: ''
  cell_type:
    description: "The cell type (default: 'markdown')"
    required: false
    default: 'markdown'
  file_pattern:
    description: "The files to target (default: '*.ipynb')"
    required: false
    default: '*.ipynb'

runs:
  using: 'composite'
  steps:
    - name: Prepend Header
      shell: bash
      run: |
        CELL_SOURCE="${{ inputs.cell_source }}"
        CELL_METADATA="${{ inputs.cell_metadata }}"
        CELL_TYPE="${{ inputs.cell_type }}"
        FILE_PATTERN="${{ inputs.file_pattern }}"

        # Find relevant files
        # Avoid .git to keep the index safe
        find . -name "$PATTERN" -not -path "./.git/*" -type f | while read -r file; do
